// Generated by tools/build_study_data.py from the user-study CSVs. Do not edit by hand.
export default {
  "intervention": {
    "success": {
      "subjects": [
        "S1",
        "S2",
        "S3",
        "S4",
        "S5",
        "S6"
      ],
      "series": [
        {
          "key": "ditto",
          "label": "DITTO-X",
          "values": [
            80.0,
            50.0,
            70.0,
            100.0,
            100.0,
            70.0
          ],
          "mean": 78.3,
          "sd": 19.4
        },
        {
          "key": "manus",
          "label": "MANUS",
          "values": [
            20.0,
            20.0,
            60.0,
            10.0,
            36.4,
            20.0
          ],
          "mean": 27.7,
          "sd": 17.9
        }
      ],
      "t": 4.45,
      "df": 5,
      "p": 0.007
    },
    "time": {
      "subjects": [
        "S1",
        "S2",
        "S3",
        "S4",
        "S5",
        "S6"
      ],
      "series": [
        {
          "key": "ditto",
          "label": "DITTO-X",
          "values": [
            36.3,
            54.7,
            41.5,
            25.2,
            24.6,
            32.1
          ],
          "mean": 35.7,
          "sd": 11.3
        },
        {
          "key": "manus",
          "label": "MANUS",
          "values": [
            80.8,
            119.1,
            47.4,
            191.9,
            59.5,
            85.6
          ],
          "mean": 97.4,
          "sd": 52.4
        }
      ],
      "t": -2.74,
      "df": 5,
      "p": 0.041
    }
  },
  "collection": {
    "success": {
      "subjects": [
        "S1",
        "S2",
        "S3",
        "S4",
        "S5",
        "S6"
      ],
      "series": [
        {
          "key": "ditto",
          "label": "DITTO-X",
          "values": [
            60.0,
            90.0,
            100.0,
            60.0,
            50.0,
            60.0
          ],
          "mean": 70.0,
          "sd": 20.0
        },
        {
          "key": "manus",
          "label": "MANUS",
          "values": [
            20.0,
            60.0,
            70.0,
            50.0,
            40.0,
            40.0
          ],
          "mean": 46.7,
          "sd": 17.5
        }
      ],
      "t": 4.72,
      "df": 5,
      "p": 0.005
    },
    "time": {
      "subjects": [
        "S1",
        "S2",
        "S3",
        "S4",
        "S5",
        "S6"
      ],
      "series": [
        {
          "key": "ditto",
          "label": "DITTO-X",
          "values": [
            80.7,
            37.5,
            50.0,
            51.8,
            78.1,
            38.4
          ],
          "mean": 56.1,
          "sd": 19.0
        },
        {
          "key": "manus",
          "label": "MANUS",
          "values": [
            157.3,
            51.2,
            52.2,
            68.4,
            126.9,
            57.1
          ],
          "mean": 85.5,
          "sd": 45.3
        }
      ],
      "t": -2.59,
      "df": 5,
      "p": 0.049
    }
  },
  "feedback": {
    "size": {
      "subjects": [
        "S1",
        "S2",
        "S3",
        "S4",
        "S5",
        "S6"
      ],
      "series": [
        {
          "key": "full",
          "label": "Force + haptics",
          "values": [
            100.0,
            83.3,
            100.0,
            66.7,
            100.0,
            66.7
          ],
          "mean": 86.1,
          "sd": 16.4
        },
        {
          "key": "force",
          "label": "Force only",
          "values": [
            66.7,
            66.7,
            66.7,
            50.0,
            66.7,
            50.0
          ],
          "mean": 61.1,
          "sd": 8.6
        },
        {
          "key": "haptics",
          "label": "Haptics only",
          "values": [
            50.0,
            33.3,
            66.7,
            50.0,
            100.0,
            66.7
          ],
          "mean": 61.1,
          "sd": 22.8
        }
      ],
      "vsFull": {
        "force": {
          "t": 6.71,
          "p": 0.001
        },
        "haptics": {
          "t": 2.67,
          "p": 0.045
        }
      },
      "df": 5,
      "chance": 33.3
    },
    "compliance": {
      "subjects": [
        "S1",
        "S2",
        "S3",
        "S4",
        "S5",
        "S6"
      ],
      "series": [
        {
          "key": "full",
          "label": "Force + haptics",
          "values": [
            83.3,
            100.0,
            100.0,
            83.3,
            83.3,
            100.0
          ],
          "mean": 91.7,
          "sd": 9.1
        },
        {
          "key": "force",
          "label": "Force only",
          "values": [
            83.3,
            100.0,
            83.3,
            66.7,
            66.7,
            83.3
          ],
          "mean": 80.6,
          "sd": 12.5
        },
        {
          "key": "haptics",
          "label": "Haptics only",
          "values": [
            50.0,
            33.3,
            83.3,
            66.7,
            16.7,
            33.3
          ],
          "mean": 47.2,
          "sd": 24.5
        }
      ],
      "vsFull": {
        "force": {
          "t": 3.16,
          "p": 0.025
        },
        "haptics": {
          "t": 4.34,
          "p": 0.007
        }
      },
      "df": 5,
      "chance": 33.3
    }
  },
  "policy": {
    "rounds": {
      "steps": [
        "Pretrain",
        "Round 1",
        "Round 2"
      ],
      "tasks": [
        {
          "task": "Tong",
          "series": [
            {
              "key": "ditto",
              "label": "DITTO-X",
              "counts": [
                [
                  19,
                  30
                ],
                [
                  22,
                  30
                ],
                [
                  26,
                  30
                ]
              ],
              "values": [
                63.3,
                73.3,
                86.7
              ]
            },
            {
              "key": "manus",
              "label": "MANUS",
              "counts": [
                [
                  4,
                  30
                ],
                [
                  12,
                  30
                ],
                [
                  11,
                  30
                ]
              ],
              "values": [
                13.3,
                40.0,
                36.7
              ]
            }
          ]
        },
        {
          "task": "Raspberry",
          "series": [
            {
              "key": "ditto",
              "label": "DITTO-X",
              "counts": [
                [
                  19,
                  30
                ],
                [
                  22,
                  30
                ],
                [
                  28,
                  30
                ]
              ],
              "values": [
                63.3,
                73.3,
                93.3
              ]
            },
            {
              "key": "manus",
              "label": "MANUS",
              "counts": [
                [
                  13,
                  30
                ],
                [
                  15,
                  30
                ],
                [
                  13,
                  30
                ]
              ],
              "values": [
                43.3,
                50.0,
                43.3
              ]
            }
          ]
        },
        {
          "task": "Battery",
          "series": [
            {
              "key": "ditto",
              "label": "DITTO-X",
              "counts": [
                [
                  12,
                  30
                ],
                [
                  17,
                  30
                ],
                [
                  27,
                  30
                ]
              ],
              "values": [
                40.0,
                56.7,
                90.0
              ]
            },
            {
              "key": "manus",
              "label": "MANUS",
              "counts": [
                [
                  10,
                  30
                ],
                [
                  14,
                  30
                ],
                [
                  14,
                  30
                ]
              ],
              "values": [
                33.3,
                46.7,
                46.7
              ]
            }
          ]
        }
      ]
    },
    "quantity": {
      "series": [
        {
          "key": "pretrain",
          "label": "Pretrain"
        },
        {
          "key": "qty",
          "label": "Quantity-matched"
        },
        {
          "key": "dagger",
          "label": "DAgger round 2"
        }
      ],
      "tasks": [
        {
          "task": "Tong",
          "counts": [
            [
              19,
              30
            ],
            [
              21,
              30
            ],
            [
              26,
              30
            ]
          ],
          "values": [
            63.3,
            70.0,
            86.7
          ]
        },
        {
          "task": "Raspberry",
          "counts": [
            [
              19,
              30
            ],
            [
              23,
              30
            ],
            [
              28,
              30
            ]
          ],
          "values": [
            63.3,
            76.7,
            93.3
          ]
        },
        {
          "task": "Battery",
          "counts": [
            [
              12,
              30
            ],
            [
              11,
              30
            ],
            [
              27,
              30
            ]
          ],
          "values": [
            40.0,
            36.7,
            90.0
          ]
        }
      ]
    }
  }
};
